In [1]:
# Numpy basics
import sys
print {sys.version}

set(['2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'])


In [2]:
import numpy as np

In [5]:
# python 2.x and python 3.x
a = 1
b = a/2
print(b)

a = 1.
b = a/2
print(b)

# in python 3.x, all variables default to float

c = [1,2,3,4]

0
0.5


In [6]:
a = np.array([1,2,3]) # define a numpy array

print(type(a)) # ndarray = n dimension array
print(a.shape)
print (a[0])

<type 'numpy.ndarray'>
(3,)
1


In [7]:
a[0] = 5
b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.shape)

(2, 3)


In [9]:
b[:,0] # the first column of b

array([1, 4])

In [10]:
b[:2,1:3] # row 0,1 and column 1,2

array([[2, 3],
       [5, 6]])

In [21]:
# create typical matrices
a = np.zeros((2,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [12]:
b = np.ones((1,2))
print(b)

[[ 1.  1.]]


In [13]:
c = np.random.randn(2,3) # generate a matrix of shape (2,3) with (n)ormal distribution
# randn(): (n)ormal -> rand(n)
print(c)

[[ 0.04415082 -0.63411196 -0.16625885]
 [ 0.91474452  0.97049838 -0.65926254]]


In [19]:
# broadcasting
a + 1

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
a += 2
a

array([[ 2.,  2.,  2.],
       [ 2.,  2.,  2.]])

In [16]:
# matrix operation
# transpose
a = np.array([[1,2,3],[3,4,5]])
print(a.T)

[[1 3]
 [2 4]
 [3 5]]


In [23]:
# dot product
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])
# x dot product y, use np.dot to compute dot product
np.dot(x,y)

40