## 1. Data type

In [238]:
d1 = 'We are A'
d2 = "We are 'B'"
d3 = "We are \
C"
d4 = '''We are 
D'''
print(d1)
print(d2)
print(d3)
print(d4)

We are A
We are 'B'
We are C
We are 
D


In [239]:
a1 = 1
type(a1)

int

In [240]:
a2 = 1.0
type(a2)

float

In [241]:
a3 = 1.0/1
type(a3)

float

In [242]:
# Bit manipulation 
c = 2**2
print 'c =', c
d = 10%3
print 'd = ', d
e = 1<<3
print 'e = ', e
e = 1>>1
print 'e = ', e
f = 15&0
print 'f = ', f
f = 15|0
print 'f = ', f
f = 15^0
print 'f = ', f
f = ~15
print 'f = ', f

c = 4
d =  1
e =  8
e =  0
f =  0
f =  15
f =  15
f =  -16


In [243]:
# logic
a = True and False
print 'a = ', a
b = True or False
print(b)

a =  False
True


## 3. Data Structures

In [244]:
# List 
# Sequential
studentList = ['Amy','Bob','Dave','Prash']
studentList2 = [1,1.5,'Amy']
print 'We have',len(studentList),'Students'

We have 4 Students


In [245]:
#
for iter in studentList:
    print(iter)

Amy
Bob
Dave
Prash


In [246]:
studentList[1]='Ann'
print studentList

['Amy', 'Ann', 'Dave', 'Prash']


In [247]:
B = 'Fanding'
studentList = ['Amy','Bob',B,'Dave','Prash']
print studentList

['Amy', 'Bob', 'Fanding', 'Dave', 'Prash']


In [248]:
studentList.append('David')
print studentList

['Amy', 'Bob', 'Fanding', 'Dave', 'Prash', 'David']


In [249]:
del studentList[0]
print studentList

['Bob', 'Fanding', 'Dave', 'Prash', 'David']


In [250]:
# 排序
studentList.sort()
print studentList

['Bob', 'Dave', 'David', 'Fanding', 'Prash']


In [251]:
# 切片
print studentList[:]
print studentList[0:2] # 末尾数字不包括在其中
print studentList[-2:]
print studentList[-2:-1]
print studentList[0:4:2]
print studentList[:-1] # 省略某个边界值
print studentList[-1]

['Bob', 'Dave', 'David', 'Fanding', 'Prash']
['Bob', 'Dave']
['Fanding', 'Prash']
['Fanding']
['Bob', 'David']
['Bob', 'Dave', 'David', 'Fanding']
Prash


In [252]:
# 常用初始化
print 'Other initialization:'
list1 = [1 for n in range(0,11)]
print list1
list2 = [n for n in range(1,11,2)]
print list2
list3 = [1]*11
print list3
# 合并
list4 = list1 + list2
print list4

Other initialization:
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 3, 5, 7, 9]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 5, 7, 9]


In [253]:
#最值
print 'Max and Min:'
print max(list4)
print min(list4)

Max and Min:
9
1


In [254]:
#其他函数
list4.reverse()
print list4

[9, 7, 5, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [255]:
# Tuple 元组
studentList = ('Bob', 'Dave', 'David', 'Fanding', 'Prash')
print len(studentList)

5


In [256]:
for i in studentList:
    print i

Bob
Dave
David
Fanding
Prash


In [257]:
# cannot do:
# studentList[1] = 'Ann'
# studentList.sort()

In [258]:
# Dictionary 字典

# hash 哈希表
studentTest = {'Bob':90, 'Dave':80, 'Fanding':81, 'Prash':90}
print len(studentTest)

4


In [259]:
# 遍历
for i in studentTest:
    print i

Fanding
Bob
Dave
Prash


In [260]:
for k,v in studentTest.items():
    print k,v

Fanding 81
Bob 90
Dave 80
Prash 90


In [261]:
print studentTest['Bob']

90


In [262]:
# 赋值
studentTest['Prash'] = 95
print(studentTest)

{'Fanding': 81, 'Bob': 90, 'Dave': 80, 'Prash': 95}


In [263]:
s = 'Dave'
if s in studentTest:
    print(studentTest[s])

80


## 4. if, while, for

In [264]:
stu1 = 'Bob'

## 5. Numpy

In [265]:
import numpy as np

# If you used to be a Matlab user, refer to the following site:
# http://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-user.html

#
a = np.array([1,2,3,4])
print a
print a.shape
print a.ndim

[1 2 3 4]
(4,)
1


In [266]:
b = np.array([[1],[2],[3],[4]])
print b
print b.shape
print b.ndim
print type(b)
print b.size

[[1]
 [2]
 [3]
 [4]]
(4, 1)
2
<type 'numpy.ndarray'>
4


In [267]:
# initialization
c = np.array([5,6,7,8])
print c 
print
print np.array([[1,2],[3,4]])
print
print np.array([1]*51).reshape(3,17)
print
print np.linspace(1,3,9)
print
print np.zeros((2,3))
print
print np.ones((3,2))
print
print np.eye(3)

[5 6 7 8]

[[1 2]
 [3 4]]

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

[ 1.    1.25  1.5   1.75  2.    2.25  2.5   2.75  3.  ]

[[ 0.  0.  0.]
 [ 0.  0.  0.]]

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [268]:
# elemen wise operation

In [269]:
# shallow copy & deep copy
# 节约内存，在opencv中也有这样的做法
# No copy
print a
print c
c = a
a[0]=100
print a
print c

[1 2 3 4]
[5 6 7 8]
[100   2   3   4]
[100   2   3   4]


In [270]:
# view
c = a.view()
print 'c = a:',c is a
print 'c.base = a:',c.base is a
c.shape = 2,2
print c.shape
print a.shape
print
# deep copy
c = a.copy()
a[0] = 10
print a
print c

c = a: False
c.base = a: True
(2, 2)
(4,)

[10  2  3  4]
[100   2   3   4]


In [271]:
a = np.array([1,2,3])
a.shape = (3,1)
print a
print
a = np.dot(a,a.transpose())
print a

[[1]
 [2]
 [3]]

[[1 2 3]
 [2 4 6]
 [3 6 9]]


## 6. Pandas 

### series:

### dataframe:

In [272]:
import numpy as np
import pandas as pd
# series
studentSeries = pd.Series(['Bob','Dave','Prash',np.nan,'David'])
print studentSeries

0      Bob
1     Dave
2    Prash
3      NaN
4    David
dtype: object


In [273]:
# dataframe
index = ['Bob','Dave','Prash','David']
studentDataFrame = pd.DataFrame({
    'Grade':np.array([1,2,3,4], dtype = 'int32'),
    'Level': pd.Categorical(['lvl1','lvl2','lvl3','lvl4']),
    'TestResult': [90,80,95,90]},
    index = index,)
print studentDataFrame

       Grade Level  TestResult
Bob        1  lvl1          90
Dave       2  lvl2          80
Prash      3  lvl3          95
David      4  lvl4          90


In [274]:
print studentDataFrame[['Level','Grade']]
print
print studentDataFrame['Bob':'Prash']

      Level  Grade
Bob    lvl1      1
Dave   lvl2      2
Prash  lvl3      3
David  lvl4      4

       Grade Level  TestResult
Bob        1  lvl1          90
Dave       2  lvl2          80
Prash      3  lvl3          95


In [275]:
# 对行和列同时切片
print studentDataFrame.iloc[0:3,0:3]

       Grade Level  TestResult
Bob        1  lvl1          90
Dave       2  lvl2          80
Prash      3  lvl3          95


In [276]:
Gender = ['F','M','F','M']
studentDataFrame['Gender'] = Gender
print studentDataFrame

       Grade Level  TestResult Gender
Bob        1  lvl1          90      F
Dave       2  lvl2          80      M
Prash      3  lvl3          95      F
David      4  lvl4          90      M


In [277]:
# obserbations
studentDataFrame.head(2)

Grade Level  TestResult Gender
Bob       1  lvl1          90      F
Dave      2  lvl2          80      M

In [278]:
studentDataFrame.tail(2)

Grade Level  TestResult Gender
Prash      3  lvl3          95      F
David      4  lvl4          90      M

In [279]:
studentDataFrame.sort_values(by = 'TestResult')

Grade Level  TestResult Gender
Dave       2  lvl2          80      M
Bob        1  lvl1          90      F
David      4  lvl4          90      M
Prash      3  lvl3          95      F